#!/usr/bin/env python3
"""
detail SVG (svg/<id>.svg) から OK/NG 食材イラストだけを抽出して
svg/parts/<id>_ok.svg / <id>_ng.svg を生成する。

抽出条件:
  - <g transform="translate(280, 320)"> ... </g>  → OK
  - <g transform="translate(800, 320)"> ... </g>  → NG
  - 各グループ先頭の <circle>(○/×バッジ)と <text>(○/×文字)はスキップ
  - 残りの内容を新しい <svg> に詰めて出力 (viewBox は VIEWBOXES で指定)

新食材追加時の使い方:
  1. svg/<id>.svg を既存と同じ構造で用意
  2. 下の VIEWBOXES に <id> エントリを追加
     (OK 食材のローカル座標が収まる viewBox を指定)
  3. python3 scripts/extract_parts.py を実行
"""
import os
import re
import sys

# 各食材ごとの viewBox (OK 食材グループのローカル座標基準)
# 適切に設定すると食材本体だけが切り出される
VIEWBOXES = {
    # 水彩風レンダリング時に十分な余白を確保。
    'daikon':   '-150 -250 300 460',
    'carrot':   '-130 -230 260 440',
    # negi は本体高さ ±25 + 回転 -15° の bbox 約485×193 に合わせて
    # 縦は短く、横は長くとる(細長感を出す)
    'negi':     '-280 -110 560 220',
    # Phase A: 9 foods (auto-generated by scripts/build_food_svgs.py)
    'tomato':   '-130 -160 260 280',
    'onion':    '-145 -210 290 380',     # re-sync: cross-section content extends further
    'egg':      '-100 -140 200 260',
    'chicken':  '-130 -110 260 220',
    'potato':   '-130 -110 260 220',
    'cabbage':  '-170 -160 340 320',     # re-sync: outer leaves extend further
    'cucumber': '-240 -65 480 130',      # re-sync: cucumber wider/thinner
    'banana':   '-180 -90 360 220',      # re-sync: side-on bunch is wider
    'apple':    '-120 -140 240 280',
    # Phase B: 23 foods (auto-generated by scripts/build_phase_b.py)
    'garlic':    '-125 -225 250 390',    # re-sync: inverted teardrop is taller
    'komatsuna': '-130 -180 260 320',
    'lettuce':   '-170 -165 340 330',    # re-sync: frilly outer leaves grew
    'hakusai':   '-95 -195 190 395',     # re-sync: tall bullet, narrower & taller
    'nasu':      '-100 -160 200 290',
    'piman':     '-110 -130 220 240',
    'broccoli':  '-130 -160 260 280',
    'ginger':    '-150 -100 300 200',
    'pumpkin':   '-130 -150 260 270',
    'shiitake':  '-110 -130 220 240',
    'shimeji':   '-130 -150 260 270',
    'enoki':     '-100 -150 200 280',
    'eringi':    '-125 -140 250 295',    # re-sync: white-cap mushroom wider
    'maitake':   '-145 -115 290 255',    # re-sync: cluster fits tighter
    'mikan':     '-100 -120 200 220',
    'lemon':     '-90 -140 180 260',
    'avocado':   '-90 -140 180 280',
    'ichigo':    '-100 -130 200 240',
    'kiwi':      '-110 -90 220 180',
    'grape':     '-100 -150 200 280',
    'peach':     '-110 -120 220 240',
    'kaki':      '-110 -120 220 220',
    'pear':      '-100 -130 200 250',
    # Phase C: 11 protein foods (auto-generated by scripts/build_phase_c.py)
    'tofu':        '-170 -95 340 195',     # re-sync: 2-face block is wider
    'natto':       '-130 -120 260 240',
    'pork':        '-130 -110 260 220',
    'beef':        '-130 -110 260 220',
    'ground_meat': '-130 -110 260 220',
    'salmon':      '-140 -90 280 180',
    'saba':        '-210 -75 420 165',     # re-sync: longer fish + back wave + finlets
    'aji':         '-195 -85 390 180',     # re-sync: longer fish + zeigo scutes
    'ebi':         '-210 -130 420 250',    # re-sync: smooth C-curve is wider
    'whole_fish':  '-160 -90 320 180',
    'yogurt':      '-100 -150 200 280',
    # Phase D: 2 game meats (auto-generated by scripts/build_phase_d.py)
    'venison':     '-130 -110 260 220',
    'boar':        '-130 -110 260 220',
}

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def extract_group(svg: str, transform: str) -> str | None:
    """<g transform="translate(transform)"> ... </g> の内側を取り出す。"""
    pattern = rf'<g\s+transform="translate\(\s*{re.escape(transform)}\s*\)"\s*>'
    m = re.search(pattern, svg)
    if not m:
        return None
    start = m.end()
    depth = 1
    pos = start
    while pos < len(svg):
        nxt_open = svg.find('<g', pos)
        nxt_close = svg.find('</g>', pos)
        if nxt_close == -1:
            return None
        if nxt_open != -1 and nxt_open < nxt_close:
            depth += 1
            pos = nxt_open + 2
        else:
            depth -= 1
            if depth == 0:
                return svg[start:nxt_close]
            pos = nxt_close + 4
    return None


def strip_badge(content: str) -> str:
    """先頭の <circle>(バッジ)と <text>(○/×)を1つずつ取り除く。"""
    content = re.sub(r'^\s*<circle[^>]*?/>\s*', '', content, count=1)
    content = re.sub(r'^\s*<text[^>]*?>[○×]</text>\s*', '', content, count=1)
    return content


def main() -> int:
    parts_dir = os.path.join(ROOT, 'svg', 'parts')
    os.makedirs(parts_dir, exist_ok=True)

    rc = 0
    for food_id, vbox in VIEWBOXES.items():
        src = os.path.join(ROOT, 'svg', f'{food_id}.svg')
        if not os.path.exists(src):
            print(f'  SKIP {food_id} (no detail SVG)', file=sys.stderr)
            continue
        with open(src, encoding='utf-8') as f:
            svg = f.read()

        ok = extract_group(svg, '280, 320')
        ng = extract_group(svg, '800, 320')
        if ok is None or ng is None:
            print(f'  FAIL {food_id} (could not locate OK/NG groups)', file=sys.stderr)
            rc = 1
            continue

        for side, raw in (('ok', ok), ('ng', ng)):
            inner = strip_badge(raw).strip()
            out = (
                f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vbox}" '
                f'font-family="Noto Sans CJK JP, sans-serif">\n'
                f'{inner}\n'
                f'</svg>\n'
            )
            dst = os.path.join(parts_dir, f'{food_id}_{side}.svg')
            with open(dst, 'w', encoding='utf-8') as f:
                f.write(out)
            print(f'  WROTE svg/parts/{food_id}_{side}.svg')

    return rc


if __name__ == '__main__':
    sys.exit(main())
